---
title: "Predictive modeling exam P4"
author: "Reece Wooten"
date: "8/1/2017"
output: html_document
---


## Problem 4 From the Exam
#### 1.
##### Describe your contribution to the “Pricing Cars” group project (1 page max)
* My contribution to the Pricing Cars group project consisted of four parts: meetings, R assignments, write up, and presentation. Group 8 met numerous times throughout the preparation process, I scheduled the first meeting where we went over the game plan for approaching the project, we laid out the timeline of the project and broke it down into steps which had deadlines. The second meeting consisted of assigning models from the textbook to run on our data. I was assigned the support vector machine, and brought the results to the third meeting where we all compared our results. Throughout the entire project, I tried numerous models past the one I was assigned, and also presented the results of those models to compare to my teammates models. Once we decided our model, which was random forest, Gaby had already ran the code in which she sent it to everyone to check, and run it for ourselves to check for any errors. Once we had our final model we began to do the write up. I was assigned the initial data analysis section where I discussed the small amount of data munging we did, and which variables appeared to provide the most information to car price just from a visual analysis. Once I finished my part in the write up, I also helped write the section that talked about the boosting models we ran, and the limitation section of the paper. Once our write up was completed we started working on the presentation, we each presented on the section we wrote about in the write up. I made numerous plots for the initial data analysis showing why we dropped some variables and our reasoning behind putting importance on certain variables. Since I was the first one to speak I also introduced the problem and introduced the team in the presentation. The weekend before the presentation the group met again to practice the presentation and make the final draft of the write up and presentation. 